"""Plot analytical-reference figures from postprocessed CSV files.

This script reads reference diagnostics generated by
``01b_postprocess_reference.py`` and writes only the three reference figures.
"""

from __future__ import annotations

import argparse
from pathlib import Path
import sys

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from pinn_spectral.tools import (  # noqa: E402
    add_overwrite_argument,
    print_skip_message,
    read_yaml,
    require_file,
    save_figure,
    should_skip,
)

EPS64 = np.finfo(np.float64).eps


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments.

    Returns
    -------
    argparse.Namespace
        Parsed arguments with configuration path and overwrite flag.
    """
    parser = argparse.ArgumentParser(description="Plot analytical-reference figures.")
    add_overwrite_argument(parser)
    parser.add_argument(
        "--config",
        default="configs/reference.yaml",
        help="Path to the reference configuration YAML file.",
    )
    return parser.parse_args()


def format_tick(value: float) -> str:
    """Format an axis tick without unnecessary trailing zeros.

    Parameters
    ----------
    value:
        Tick value to format.

    Returns
    -------
    str
        Compact decimal string.
    """
    return f"{float(value):.3f}".rstrip("0").rstrip(".")


def plot_temporal_convergence(input_path: Path, output_path: Path) -> None:
    """Create the temporal convergence reference figure.

    Parameters
    ----------
    input_path:
        CSV with columns ``t`` and ``error_l2``.
    output_path:
        Figure path for ``fig01_temporal_convergence.png``.
    """
    df = pd.read_csv(input_path)
    required = {"t", "error_l2"}
    if not required.issubset(df.columns):
        raise ValueError(f"{input_path} must contain columns: {sorted(required)}")

    nonzero = df[df["error_l2"] > 0.0]
    t_nonzero = float(nonzero["t"].iloc[-1]) if not nonzero.empty else None

    fig, ax = plt.subplots(figsize=(6.5, 4.2))
    ax.semilogy(df["t"], df["error_l2"], color="black", linewidth=1.5)
    ax.axhline(EPS64, color="0.45", linestyle="--", linewidth=0.9, label=r"$\epsilon_{64}$")

    if t_nonzero is not None:
        ax.axvline(t_nonzero, color="black", linestyle=":", linewidth=1.0)
        current_ticks = [float(tick) for tick in ax.get_xticks()]
        ticks = sorted(
            set(
                tick
                for tick in current_ticks + [t_nonzero]
                if float(df["t"].min()) <= tick <= float(df["t"].max())
            )
        )
        ax.set_xticks(ticks)
        ax.set_xticklabels([format_tick(tick) for tick in ticks], rotation=90)
        print(f"Temporal convergence: largest nonzero-error sampled time = {t_nonzero:.16e}")

    ax.set_xlabel(r"$t$")
    ax.set_ylabel(r"$\|u_N(x_j,t)-S(x_j)\|_{\ell^2_{\{x_j\}}}$")
    ax.grid(True, which="both", linestyle="--", linewidth=0.5, alpha=0.7)
    ax.legend(fontsize=8)
    fig.tight_layout()
    save_figure(output_path)
    plt.close(fig)


def plot_endpoint_curve(ax: plt.Axes, group: pd.DataFrame, k_int: int) -> bool:
    """Plot one averaging-width curve on a log-log endpoint figure.

    Parameters
    ----------
    ax:
        Matplotlib axes receiving the curve.
    group:
        Subset of the endpoint DataFrame for one ``K`` value.
    k_int:
        Averaging width used for the legend.

    Returns
    -------
    bool
        ``True`` if at least one valid positive value was plotted.
    """
    group = group.sort_values("N")
    n = group["N"].to_numpy(dtype=np.float64)
    y_raw = group["error_l2"].to_numpy(dtype=np.float64)
    if n.size == 0:
        return False

    y_plot = y_raw.copy()
    finite = np.isfinite(y_plot)
    y_plot[~finite] = np.nan
    y_plot[finite & (y_plot < EPS64)] = EPS64
    valid = np.isfinite(y_plot) & (y_plot > 0.0)
    if not np.any(valid):
        return False

    if k_int == 1:
        ax.loglog(n[valid], y_plot[valid], label=rf"$K={k_int}$", color="black", linestyle="--", linewidth=1.4, zorder=10)
    else:
        ax.loglog(n[valid], y_plot[valid], label=rf"$K={k_int}$", linewidth=1.2)
    return True


def print_target_error(df: pd.DataFrame, label: str, n_target: int = 100000, k_target: int = 10000) -> None:
    """Print the diagnostic error at the manuscript reference values.

    Parameters
    ----------
    df:
        Endpoint diagnostic DataFrame.
    label:
        Console label describing the diagnostic.
    n_target, k_target:
        Truncation and averaging width to report.
    """
    target = df[(df["N"] == int(n_target)) & (df["K"] == int(k_target))]
    if target.empty:
        print(f"{label}: error at N={n_target}, K={k_target} not found in CSV.")
        return
    value = float(target["error_l2"].iloc[0])
    print(f"{label}: error_l2 at N={n_target}, K={k_target} = {value:.16e}")


def plot_endpoint_consistency(input_path: Path, output_path: Path, ylabel: str, console_label: str) -> None:
    """Create an endpoint consistency figure from a diagnostic CSV.

    Parameters
    ----------
    input_path:
        CSV with columns ``N``, ``K``, and ``error_l2``.
    output_path:
        Figure path.
    ylabel:
        Vertical-axis label.
    console_label:
        Label used for printing the target diagnostic value.
    """
    df = pd.read_csv(input_path)
    required = {"N", "K", "error_l2"}
    if not required.issubset(df.columns):
        raise ValueError(f"{input_path} must contain columns: {sorted(required)}")

    print_target_error(df, console_label)
    fig, ax = plt.subplots(figsize=(6.5, 4.2))
    plotted_any = False
    for k, group in df.groupby("K", sort=True):
        plotted_any = plot_endpoint_curve(ax, group, int(k)) or plotted_any

    ax.set_xlabel(r"$N$")
    ax.set_ylabel(ylabel)
    ax.grid(True, which="both", linestyle="--", linewidth=0.5, alpha=0.7)
    if plotted_any:
        ax.legend(fontsize=8)
    fig.tight_layout()
    save_figure(output_path)
    plt.close(fig)


def main() -> None:
    """Generate all analytical-reference figures."""
    args = parse_args()
    config_path = Path(args.config)
    if not config_path.is_absolute():
        config_path = ROOT / config_path
    config = read_yaml(config_path)
    outputs = config["outputs"]
    postprocess_dir = ROOT / outputs.get("postprocess_dir", "results/postprocess/reference")
    figure_dir = ROOT / outputs.get("figure_dir", "results/figures/reference")

    temporal_csv = postprocess_dir / "temporal_convergence.csv"
    initial_csv = postprocess_dir / "initial_consistency.csv"
    stationary_csv = postprocess_dir / "stationary_consistency.csv"
    for path in [temporal_csv, initial_csv, stationary_csv]:
        require_file(path, "Run: python scripts\\01b_postprocess_reference.py --overwrite")

    figure_paths = [
        figure_dir / "fig01_temporal_convergence.png",
        figure_dir / "fig02_initial_consistency.png",
        figure_dir / "fig03_stationary_consistency.png",
    ]
    if should_skip(figure_paths, overwrite=args.overwrite):
        print_skip_message(figure_paths, ROOT)
        return

    plot_temporal_convergence(temporal_csv, figure_paths[0])
    plot_endpoint_consistency(
        initial_csv,
        figure_paths[1],
        ylabel=rf"$\|\bar{{u}}_N^{{(K)}}(x_j,0)-f(x_j)\|_{{\ell^2_{{\{{x_j\}}}}}}$",
        console_label="Initial consistency",
    )
    plot_endpoint_consistency(
        stationary_csv,
        figure_paths[2],
        ylabel=rf"$\|\bar{{u}}_N^{{(K)}}(x_j,T)-S(x_j)\|_{{\ell^2_{{\{{x_j\}}}}}}$",
        console_label="Stationary consistency",
    )

    print("Saved reference figures:")
    for path in figure_paths:
        print(f"  {path.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
