"""Plot finite-difference baseline figures from postprocessed CSV files.

This script reads diagnostics generated by ``02b_postprocess_numerical.py`` and
writes only the finite-difference error figures.
"""

from __future__ import annotations

import argparse
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from pinn_spectral.tools import (  # noqa: E402
    add_overwrite_argument,
    compute_pooled_log_ylim,
    error_space_source_paths,
    error_time_source_paths,
    plot_grouped_error_curves,
    print_skip_message,
    read_yaml,
    require_file,
    should_skip,
)


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments.

    Returns
    -------
    argparse.Namespace
        Parsed arguments with configuration path and overwrite flag.
    """
    parser = argparse.ArgumentParser(description="Plot finite-difference baseline figures.")
    add_overwrite_argument(parser)
    parser.add_argument(
        "--config",
        default="configs/numerical.yaml",
        help="Path to the numerical configuration YAML file.",
    )
    return parser.parse_args()


def plot_numerical_error_time(input_path: Path, output_path: Path, ylim: tuple[float, float] | None) -> None:
    """Create the finite-difference time-error figure.

    Parameters
    ----------
    input_path:
        CSV with columns ``method``, ``label``, ``t``, and ``error_l2``.
    output_path:
        Figure path for ``fig01_fdm_error_time.png``.
    ylim:
        Shared ``E(t)`` limits pooled across every stage, or ``None`` to fall
        back to this figure's own data.
    """
    plot_grouped_error_curves(
        input_path=input_path,
        output_path=output_path,
        x_column="t",
        xlabel=r"$t$",
        ylabel=r"$E(t)$",
        ylim=ylim,
    )


def plot_numerical_error_space(input_path: Path, output_path: Path, ylim: tuple[float, float] | None) -> None:
    """Create the finite-difference space-error figure.

    Parameters
    ----------
    input_path:
        CSV with columns ``method``, ``label``, ``x``, and ``error_l2``.
    output_path:
        Figure path for ``fig02_fdm_error_space.png``.
    ylim:
        Shared ``E(x)`` limits pooled across every stage, or ``None`` to fall
        back to this figure's own data.
    """
    plot_grouped_error_curves(
        input_path=input_path,
        output_path=output_path,
        x_column="x",
        xlabel=r"$x$",
        ylabel=r"$E(x)$",
        ylim=ylim,
    )


def main() -> None:
    """Generate all finite-difference baseline figures."""
    args = parse_args()
    config_path = Path(args.config)
    if not config_path.is_absolute():
        config_path = ROOT / config_path
    config = read_yaml(config_path)
    outputs = config["outputs"]
    postprocess_dir = ROOT / outputs.get("postprocess_dir", "results/postprocess/numerical")
    figure_dir = ROOT / outputs.get("figure_dir", "results/figures/numerical")

    time_csv = postprocess_dir / "fdm_error_time.csv"
    space_csv = postprocess_dir / "fdm_error_space.csv"
    for path in [time_csv, space_csv]:
        require_file(path, "Run: python scripts\\02b_postprocess_numerical.py --overwrite")

    figure_paths = [
        figure_dir / "fig01_fdm_error_time.png",
        figure_dir / "fig02_fdm_error_space.png",
    ]
    if should_skip(figure_paths, overwrite=args.overwrite):
        print_skip_message(figure_paths, ROOT)
        return

    time_ylim = compute_pooled_log_ylim(error_time_source_paths(ROOT))
    space_ylim = compute_pooled_log_ylim(error_space_source_paths(ROOT))
    plot_numerical_error_time(time_csv, figure_paths[0], time_ylim)
    plot_numerical_error_space(space_csv, figure_paths[1], space_ylim)

    print("Saved numerical figures:")
    for path in figure_paths:
        print(f"  {path.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
