"""Run progressive physics-informed training over ``0 <= t <= 5``.

The network architecture is read from the metadata generated by
``03b_postprocess_nas.py``. Only the architecture is transferred; PINN weights
are initialized with the Xavier routine implemented by ``FullyConnectedNN``.
Each completed temporal window is stored as an atomic artifact bundle so an
interrupted run resumes from the first missing window without skipping work.
"""

from __future__ import annotations

import argparse
from pathlib import Path
import sys
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from pinn_spectral.pinn import run_progressive_pinn_training  # noqa: E402
from pinn_spectral.tools import add_overwrite_argument, read_yaml  # noqa: E402


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(description="Run progressive PINN training.")
    add_overwrite_argument(parser)
    parser.add_argument(
        "--config",
        default="configs/pinn.yaml",
        help="Path to the PINN configuration YAML file.",
    )
    return parser.parse_args()


def load_pinn_config(config_path: str | Path) -> dict[str, Any]:
    """Load the PINN YAML configuration from a project-relative path."""
    path = Path(config_path)
    if not path.is_absolute():
        path = ROOT / path
    return read_yaml(path)


def main() -> None:
    """Run or resume all progressive PINN windows."""
    args = parse_args()
    config = load_pinn_config(args.config)
    summary = run_progressive_pinn_training(config, root=ROOT, overwrite=args.overwrite)

    print("PINN training stage complete:")
    print(f"  architecture: {summary['architecture']['name']}")
    print(f"  windows: {summary['completed_windows']}/{summary['expected_windows']}")
    print(f"  final solution: {summary['final_solution']}")
    print(f"  final checkpoint: {summary['final_checkpoint']}")
    print(f"  window metrics: {summary['windows_csv']}")
    print(f"  metadata: {summary['training_metadata']}")


if __name__ == "__main__":
    main()
